### ISSUE TITLE
Sprite

### ISSUE THREAD

**Issue by thompsonemerson** [willianjusten/svg-workflow#1]
Fala @willianjusten, tranquilo?
Poh, poderia aproveitar e adicionar uma feature para gerar um sprite com os svg's  otimizados. ou seria apenas pra otimizar mesmo?

**Comment by willianjusten** [comment]
Opa, ele já gera um sprite sim, dentro da pasta `build` usando o [grunt-svgstore](https://github.com/FWeinb/grunt-svgstore).

**Comment by thompsonemerson** [comment]
Pode crê!
